### ISSUE TITLE
Allocation error using updated database ST

### ISSUE THREAD

**Issue by Dx-wmc** [MAphd/PAMLST#1]
Hi, I used the -u option of the script to update the database, but when I used the updated database for MLST, I found that a large number of strains were assigned as 9999, which is obviously incorrect. So I ran it again using the un-updated database and got the correct result. However, since STs are continuously updated, is it possible to optimize the script for updating databases?

**Comment by MAphd** [comment]
Hi, I'm having trouble replicating your error. If possible can you send one or more of the genomes that are assigned as 9999 (or provide NCBI accession numbers)?

**Comment by Dx-wmc** [comment]
Yes, for example. I used the genome (No.Acc: GCF_000480435.1) as input by the updated database (`Rscript PAMLST.R -u`), it was assigned as 9999. However, the real ST is 2627.

**Comment by MAphd** [comment]
So it seems like pubMLST included a bunch of _acsA_ alleles that are similar to a region in the _acsB_ gene, which is causing issues with this script. With the updated database, the script finds two _acsA_ alleles: _acsA_ 16 and _acsA_ 347 in different contigs of GCF_000480435.1 and deems it untypable because of it. So, updating the database does work, but I will work on a workaround for this specific issue in the near future. Thanks for letting me know.

**Comment by Dx-wmc** [comment]
Hope to see the updated version soon.
